services:
  book-service:
    build:
      context: ./backend/book-service
      dockerfile: Dockerfile
    container_name: bookstore_book_service
    ports:
      - "3000:3000"
    env_file:
      - path: book-service.env
        required: false
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      BOOKS_TABLE_NAME: ${BOOKS_TABLE_NAME:-tb_books}
      NODE_ENV: ${NODE_ENV:-development}
    networks:
      - back-tier

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookstore_frontend
    ports:
      - "80:80"
    environment:
      NGINX_PORT: "80"
      PROXY_PASS: "http://book-service:3000"
    env_file:
      - path: frontend.env
        required: false
    depends_on:
      - book-service
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
